### ISSUE TITLE
Exception when calling AriesClient.outOfBandCreateInvitation

### ISSUE THREAD

**Issue by jhoar** [hyperledger-labs/acapy-java-client#62]
I have found a when calling AriesClient.outOfBandCreateInvitation

There is a demo project which shows the problem with a unit test (using Jersey for the REST server):

https://github.com/jhoar/ajc-oob-invite

There is no exception dump in 0.7.26 and 0.7.27, but in 0.7.28 I get back:

...
[qtp201556483-20] INFO RestHandler - topic: out_of_band, payload: {"created_at": "2022-08-27T13:21:42.529712Z", "invitation": {"@type": "https://didcomm.org/out-of-band/1.0/invitation", "@id": "ce5048da-190c-40e2-946a-95a175528ef9", "label": "oobinv.agent", "services": [{"id": "#inline", "type": "did-communication", "recipientKeys": ["did:key:z6MkvabGhkcSKSZ9jcxevULqUnmmez8kww8p92chKF9xCLZp"], "serviceEndpoint": "http://172.17.0.1:8020/"}], "handshake_protocols": ["https://didcomm.org/didexchange/1.0", "https://didcomm.org/connections/1.0"]}, "connection_id": "41356875-7902-4d9c-b938-6dfe61325a32", "trace": false, "invi_msg_id": "ce5048da-190c-40e2-946a-95a175528ef9", "state": "await-response", "role": "sender", "oob_id": "8801ba6f-df9f-4429-ac08-21b2132f7893", "updated_at": "2022-08-27T13:21:42.529712Z", "our_recipient_key": "H8LE7WMzyu4gd87xEuNzdhDmqQruY3tTT1hmUyBwH7nS"}
[qtp201556483-17] INFO RestHandler - topic: connections, payload: {"created_at": "2022-08-27T13:21:42.505967Z", "connection_protocol": "didexchange/1.0", "connection_id": "41356875-7902-4d9c-b938-6dfe61325a32", "their_role": "invitee", "state": "invitation", "invitation_key": "H8LE7WMzyu4gd87xEuNzdhDmqQruY3tTT1hmUyBwH7nS", "rfc23_state": "invitation-sent", "accept": "auto", "invitation_msg_id": "ce5048da-190c-40e2-946a-95a175528ef9", "routing_state": "none", "updated_at": "2022-08-27T13:21:42.505967Z", "invitation_mode": "once", "alias": "foo"}
[qtp201556483-20] ERROR org.hyperledger.aries.webhook.EventParser - Could not format json body
com.google.gson.JsonSyntaxException: Failed parsing 'H8LE7WMzyu4gd87xEuNzdhDmqQruY3tTT1hmUyBwH7nS' as UUID; at path $.our_recipient_key
        at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:565)
        at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:554)
....

The ACAPY config is in runAcapy.sh (using docker and a local von-network instance, also docker).

Any suggestions?

Thanks!

john

**Comment by etschelp** [comment]
Thanks for the detailed description, and for the test, it always helps tremendously to have steps to reproduce a behaviour. What you are seeing was introduced with:  https://github.com/hyperledger-labs/acapy-java-client/pull/59 where I added a handler method for the OOB event, unfortunately I overlooked the fact that `our_recipient_key` is not a UUID. This is now fixed, and I will release a new version this week. The exception is not fatal and will only clutter your logs, unless you require the event in the handler.

**Comment by etschelp** [comment]
Fixed with 0.7.29
